apiVersion: v1
kind: ConfigMap
metadata:
  name: novus-code-config
data:
  PORT: "3001"
  AWS_BUCKET_NAME: novus-code
  CLIENT_ORIGINS: https://novuscode.novus02.in/,http://localhost:5173,http://localhost:4173
  COPY_DIST: ./../../../../s3-code
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  FRONTEND_URL: https://novuscode.novus02.in/
  BACKEND_URL: https://api.novus02.in/